// vue-3/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import Desk from "./components/Desk.vue";

const keyComponent = ref<string | number>(Math.random())

const changeKey = (): void => {
  keyComponent.value = Math.random()
}

</script>

<template>
  <main class="container">
    <Desk :key="keyComponent" @reload="changeKey"/>
  </main>
</template>

<style scoped>
.container {
    display: grid;
    height: 90vh;
    aspect-ratio: 1;
}
</style>

// react/src/App.jsx
import { useState } from 'react'
import Desk from "./components/Desk/Desk";
import './App.css'

function App() {
  const [keyComponent, setKeyComponent] = useState(Math.random());

  function changeKey() {
    setKeyComponent(Math.random());
  }
  return (
    <main className="container">
      <Desk 
      key={keyComponent} 
      reload={changeKey}
      />
    </main>
  )
}

export default App
